import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const developmentPreviewMeta =
  /<meta(?=[^>]*\bname=["']codex-preview["'])(?=[^>]*\bcontent=["']development["'])[^>]*>/i;

test("renders development preview metadata", async () => {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  const response = await worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );

  assert.equal(response.status, 200);
  assert.match(
    response.headers.get("content-type") ?? "",
    /^text\/html\b/i,
  );
  const html = await response.text();
  assert.match(html, developmentPreviewMeta);
  assert.match(html, /ShipStation Tools/);
  assert.match(html, /Amazon Tools/);
  assert.match(html, /StockLens v(?:<!-- -->)?5\.66\.7/);

  const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const workerSource = await readFile(new URL("../worker/index.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(pageSource, /Amazon Replenishment/);
  assert.match(pageSource, /INTERNAL PROCESS MONITOR/);
  assert.match(pageSource, /What would you like to work on\?/);
  assert.match(pageSource, /Customize StockLens/);
  assert.match(pageSource, /Unlock customization/);
  assert.match(pageSource, /stocklens-interface-theme/);
  assert.match(pageSource, /data-ui-preview="true"/);
  assert.match(pageSource, /Ocean blue/);
  assert.match(pageSource, /Dark/);
  assert.match(pageSource, /Midnight blue/);
  assert.match(pageSource, /Forest night/);
  assert.match(pageSource, /Text &amp; size/);
  assert.match(pageSource, /Menu order/);
  assert.match(pageSource, /stocklens-interface-preferences/);
  assert.match(pageSource, /data-menu-scope="main"/);
  assert.match(pageSource, /Continue current list/);
  assert.match(pageSource, /Work on an old list/);
  assert.match(pageSource, /Start a new list/);
  assert.match(pageSource, /amazonReplenishmentEntryView/);
  assert.match(pageSource, /View all \{process\.length\} internal stages/);
  assert.match(pageSource, /Administrator key/);
  assert.match(pageSource, /processStepKey/);
  assert.match(pageSource, /HARD GATE — ORLANDO LIST REQUIRES REVIEW/);
  assert.match(pageSource, /StockLens Amazon replacement decision master/);
  assert.match(workerSource, /GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT/);
  assert.match(workerSource, /\/api\/amazon\/replenishment\/runs/);
  assert.match(workerSource, /\/api\/amazon\/replenishment\/decisions/);
  assert.match(workerSource, /amazon_replenishment_item_decision/);
  assert.match(workerSource, /America\/New_York/);
  assert.match(workerSource, /googleDrive: googleDriveStatus/);
  assert.match(workerSource, /no worksheet contains both a Current Barcode\/Item Number column and a SKU\/Item SKU column/);
  assert.match(workerSource, /readNightlyWohItems\(wohBuffer\)/);
  assert.match(workerSource, /\/api\/inventory\/current-ledger/);
  assert.match(workerSource, /includeItemsFromAllDrives: "true"/);
  assert.match(pageSource, /downloadInventoryMovesThroughCentralConnection/);
  assert.match(pageSource, /central-drive-current-ledger/);
  assert.match(pageSource, /Google Drive connected · retry ready/);
  assert.match(pageSource, /START UPLOAD AND CREATE THE BASELINE/);
  assert.match(pageSource, /ebayInventoryUploadSnapshot/);
  assert.match(pageSource, /Run nightly review again now/);
  assert.match(pageSource, /EBAY\/WOH UPDATE PROCESS/);
  assert.match(pageSource, /Retry failed update/);
  assert.match(pageSource, /The mapping session remains open because the permanent eBay\/WOH update failed/);
  assert.match(pageSource, /Promise\.allSettled/);
  assert.match(pageSource, /Start eBay upload/);
  assert.match(pageSource, /0 → X/);
  assert.match(pageSource, /X → 0/);
  assert.match(pageSource, /Quantity overrides/);
  assert.match(pageSource, /Confirmed items/);
  assert.match(pageSource, /Ready to upload/);
  assert.match(pageSource, /Export Ready to upload · Excel/);
  assert.match(pageSource, /Decisions remain editable/);
  assert.match(pageSource, /abc-available-list/);
  assert.match(workerSource, /\/api\/ebay\/inventory\/update-quantity/);
  assert.match(workerSource, /\/api\/ebay\/inventory\/review-snapshot/);
  assert.match(workerSource, /\/api\/ebay\/inventory\/upload-result\/download/);
  assert.match(pageSource, /Download saved pre-upload baseline/);
  assert.match(pageSource, /Download complete post-upload result/);
  assert.match(pageSource, /body: JSON\.stringify\(\{ reviewId: committed\.reviewId, rowIndex: index \}\)/);
  assert.match(pageSource, /baseline will be saved only when upload starts/);
  assert.doesNotMatch(pageSource, /const locked = lockEbayInventoryUploadSnapshot\(results, \{\}\);\s*await commitEbayInventoryUploadSnapshot\(locked\)/);
  assert.match(pageSource, /import \{ ebayReviewFingerprint \} from "@\/lib\/ebay-review-fingerprint"/);
  assert.match(workerSource, /import \{ ebayReviewFingerprint \} from "\.\.\/lib\/ebay-review-fingerprint"/);
  assert.match(pageSource, /BACKGROUND PRELOAD/);
  assert.match(pageSource, /Use latest saved fetch/);
  assert.match(pageSource, /Download new eBay inventory/);
  assert.match(pageSource, /Cancel override/);
  assert.match(pageSource, /Start inventory analysis/);
  assert.match(pageSource, /INVENTORY ANALYSIS PROCESS/);
  assert.match(pageSource, /Allocate shared inventory/);
  assert.match(pageSource, /No results were committed/);
  assert.match(pageSource, /The previous completed review is preserved and will reappear/);
  assert.match(pageSource, /Retry analysis/);
  assert.match(pageSource, /Equivalent allocation became too complex/);
  assert.match(pageSource, /Checking independent capacity/);
  assert.match(pageSource, /Distributing shared stock/);
  assert.match(pageSource, /await calculateEbayInventoryWithEquivalents/);
  assert.match(pageSource, /stocklens-ebay-analysis-diagnostic/);
  assert.match(pageSource, /EBAY_INVENTORY_REVIEW_PAGE_SIZE = 75/);
  assert.match(pageSource, /ebayInventoryReviewPageItems\.map/);
  assert.match(pageSource, /Filters apply to all rows/);
  assert.match(pageSource, /Previous 75/);
  assert.match(pageSource, /Next 75/);
  assert.match(pageSource, /function ebayInventoryUploadFingerprint\(items: EbayInventorySyncItem\[\]\)/);
  assert.doesNotMatch(pageSource, /const ebayInventoryUploadFingerprint\s*=/);
  assert.match(pageSource, /X → 0 ALTERNATE-COMPONENT REVIEW/);
  assert.match(pageSource, /0 → 0 OPTIONAL ALTERNATE-COMPONENT REVIEW/);
  assert.match(pageSource, /\["zero-zero", "0 → 0", ebayZeroToZeroItems\.length\]/);
  assert.match(pageSource, /This 0 → 0 review is optional and does not block upload/);
  assert.match(pageSource, /Grouped by the limiting WOH component/);
  assert.match(pageSource, /One substitution applies to the whole group/);
  assert.match(pageSource, /Manage for all/);
  assert.match(pageSource, /No alternate for all affected listings/);
  assert.match(pageSource, /The resolved group was removed from the 0 → 0 and X → 0 review queues/);
  assert.match(pageSource, /Number\(b\.id\.startsWith\("original:"\)\) - Number\(a\.id\.startsWith\("original:"\)\) \|\| capacity/);
  assert.match(pageSource, /Substitution saved and verified\. Recalculating every affected eBay listing/);
  assert.match(pageSource, /Number\(b\.currentQuantity > 0\) - Number\(a\.currentQuantity > 0\)/);
  assert.match(pageSource, /Every listing reduced from a positive quantity to zero remains here/);
  assert.match(pageSource, /Manage/);
  assert.match(pageSource, /Confirm alternate decision/);
  assert.match(pageSource, /Reopen alternate decision/);
  assert.match(pageSource, /Cancel No replacement/);
  assert.match(pageSource, /saved alternate paths/);
  assert.doesNotMatch(pageSource, /setEbayInventorySyncError\(""\);\s*setEbayInventorySyncItems\(\[\]\)/);
  assert.match(workerSource, /\/api\/ebay\/inventory\/listing-fetches/);
  assert.match(workerSource, /ORDER BY fetched_at DESC, id DESC LIMIT 5/);
  assert.match(workerSource, /saveEbayInventoryListingFetch\(env, payload\.listings, "Nightly inventory review"\)/);
  assert.match(pageSource, /FINAL VIEW · ORLANDO TAB/);
  assert.match(pageSource, /Confirm replacement decision/);
  assert.match(pageSource, /Confirm qty/);
  assert.match(pageSource, /Anotar Ultimos 4 del UPC que se uso y sticker si aplica/);
  assert.match(pageSource, /plan-column-resizer/);
  assert.match(pageSource, /plan-filter-popover/);
  assert.match(pageSource, /amazon-replacement-drawer/);
  assert.match(styles, /size:letter landscape/);
  assert.match(pageSource, /Replace component/);
  assert.match(pageSource, /Alternate qty per 1 original/);
  assert.match(pageSource, /Display or hide Orlando columns/);
  assert.match(pageSource, /Open finalized Google Drive folder/);
  assert.match(pageSource, /UPC number/);
  assert.doesNotMatch(pageSource, /ScannableEanBarcode/);
  assert.match(pageSource, /Approved rows/);
  assert.match(pageSource, /Take off list/);
  assert.match(pageSource, /findWohKeywordMatches\(rows, replacementSearch/);
  assert.match(pageSource, /const searchable = Object\.values\(row\)/);
  assert.match(pageSource, /const liveRows = await loadWohRowsWithStock\(token\)/);
  assert.match(pageSource, /WOH candidate results/);
  assert.match(pageSource, /WOH items loaded/);
  assert.match(pageSource, /Show broader matches/);
  assert.match(pageSource, /line\.unitsSoldLast30Days\.toLocaleString/);
  assert.match(pageSource, /adv cst/);
  assert.match(pageSource, /storage cost/);
  assert.match(pageSource, /profitability \(pft\/cst\)/);
  assert.match(pageSource, /Obs June 25/);
  assert.match(pageSource, /Total \$ value/);
  assert.match(pageSource, /actual variance/);
  assert.match(pageSource, /Session quantity confirmed · not saved permanently/);
  assert.doesNotMatch(pageSource, /amazonReplenishmentJson\("\/api\/amazon\/replenishment\/decisions/);
  assert.doesNotMatch(pageSource, /Quantity sold in the last 30 days/);
  assert.doesNotMatch(pageSource, /recommendedShipDate \|\| "No ship date"/);
  assert.match(pageSource, /const printFinalTable/);
  assert.match(pageSource, /display: table-header-group/);
  assert.match(pageSource, /printWindow\.print\(\)/);
  assert.match(pageSource, /const buildAmazonOrlandoPdf = \(presentation\?: AmazonOrlandoPresentation\)/);
  assert.match(pageSource, /presentation\?\.visibleColumns/);
  assert.match(pageSource, /presentation\?\.columnWidths\[column\.key\]/);
  assert.match(pageSource, /pdf\.addPage\(\); y = drawHeader\(margin\)/);
  assert.match(pageSource, /buildAmazonOrlandoPdf\(presentation\)\.output\("blob"\)/);
  assert.match(pageSource, /new Set<AmazonOrlandoColumnKey>\(\["sellerSku", "qty"\]\)/);
  assert.match(pageSource, /enlargedSkuFontSize = bodyFontSize \* 1\.25/);
  assert.match(pageSource, /styledWrappedLines\(`UPC \$\{detail\.upc \|\| "—"\}`, width\)/);
  assert.match(pageSource, /inventory", label: "Inv Hallandale", width: 78/);
  assert.match(styles, /orlando-col-sellerSku,\.amazon-orlando-table \.orlando-col-qty\{background:#ffe95c\}/);
  assert.match(pageSource, /onFinalize\(orlandoPresentation\(\)\)/);
  assert.match(workerSource, /settings_json AS settingsJson/);
  assert.match(pageSource, /"Carrier Fee", "CarrierFee", "Shipping Cost"/);
  assert.match(pageSource, /"Record #", "Record Number"/);
  assert.match(pageSource, /labelVoided/);
  assert.match(pageSource, /const averageShippingValue/);
  assert.match(pageSource, /const canonicalWohShippingKey/);
  assert.match(pageSource, /const wohPrimaryReferenceKeys/);
  assert.match(pageSource, /for \(const row of rows\) for \(const key of wohPrimaryReferenceKeys\(row\)\)/);
  assert.match(pageSource, /WOH Shipping Estimate Before Adjustment/);
  assert.match(pageSource, /Monthly Shipping Adjustment Factor/);
  assert.match(pageSource, /function mergeShippingRateRecords/);
  assert.match(pageSource, /function savedShippingRateForRow/);
  assert.match(pageSource, /for \(const rate of rates\.values\(\)\) addShippingRateRecord\(canonicalRates, rate\.wohSku, rate\)/);
  assert.match(pageSource, /"SL Item Class",\s*"AMZ Item Class",\s*"eBay Item Class"/);
  assert.match(pageSource, /<th>SL class<\/th>\s*<th>AMZ class<\/th>\s*<th>eBay class<\/th>/);
  assert.match(pageSource, /function buildEbayAbcComponentUsage/);
  assert.match(pageSource, /WOH Component Summary/);
  assert.match(pageSource, /Component Where Used/);
  assert.match(pageSource, /Cumulative Parent Profit/);
  assert.match(pageSource, /stocklens-purchasing-quote-master\.xlsx/);
  assert.match(pageSource, /Export filtered vendor Excel files/);
  assert.match(pageSource, /Upload vendor quote/);
  assert.match(pageSource, /Save decisions/);
  assert.match(pageSource, /Columns & table settings/);
  assert.match(pageSource, /stocklens-restock-columns/);
  assert.match(pageSource, /MAKE OR BUY DECISION/);
  assert.match(pageSource, /Permanent decision history/);
  assert.match(pageSource, /CLASS DECISION TABLE/);
  assert.match(pageSource, /Parent Cumulative Profit Percent/);
  assert.match(pageSource, /Make \/ Buy/);
  assert.match(pageSource, /rolled down to component quantities/);
  assert.match(pageSource, /eBay\/WOH mapping/);
  assert.match(pageSource, /Shopify\/WOH mapping/);
  assert.match(pageSource, /Amazon\/WOH mapping/);
  assert.match(pageSource, /non-assembly default/i);
  assert.match(pageSource, /Save better match/);
  assert.match(pageSource, /Item Definitions/);
  assert.match(pageSource, /Calculation Trace/);
  assert.match(pageSource, /Order Calculation Trace/);
  assert.match(pageSource, /Recorded Net eBay Proceeds - Landed \/ Assembly Cost/);
  assert.match(pageSource, /Revenue-to-proceeds audit/);
  assert.match(pageSource, /View calculation trace/);
  assert.match(pageSource, /WOH Component Cost JSON/);
  assert.match(pageSource, /One table for every supplier/);
  assert.match(pageSource, /Export filtered vendor Excel files/);
  assert.match(pageSource, /Export filtered supplier PDFs/);
  assert.match(pageSource, /stocklens-restock-column-widths-v3/);
  assert.match(pageSource, /Negative only/);
  assert.match(pageSource, /All signed/);
  assert.match(pageSource, /WOH Make \/ Buy/);
  assert.match(pageSource, /Planning group/);
  assert.match(pageSource, /"Buy\/Make", "Buy \/ Make", "Make \/ Buy"/);
  assert.match(pageSource, /makeBuy === "Make" \? "Assembly" : "Non-assembly"/);
  assert.match(pageSource, /return value === "make" \? "Make"/);
  assert.doesNotMatch(pageSource, /value === "make" \|\| value === "assembly"/);
  assert.doesNotMatch(pageSource, /Make suggestion pending user confirmation/);
  assert.doesNotMatch(pageSource, /The current status has not changed\. Review and confirm before saving this item as an assembly/);
  assert.doesNotMatch(pageSource, /Review as Assembly/);
  assert.match(pageSource, /Permanent user decision · future analyses will preserve it/);
  assert.match(pageSource, /Recovered permanent user decision from mapping history/);
  assert.match(pageSource, /historicalUserDecisionByKey/);
  assert.match(pageSource, /latestHistoryChangeByKey/);
  assert.match(pageSource, /change\.changed_at > current\.changed_at/);
  assert.match(workerSource, /automatic_rule_updated/);
  assert.match(pageSource, /wohPrimaryReferenceKeys\(row\)\.includes\(cleanSku\(component\.sku\)\)/);
  assert.match(pageSource, /assignEbayAssemblyComponent\(mapping\.key, editingEbayComponent\.index, wohMappingSku\(row\)\)/);
  assert.match(pageSource, /"Knowledge Source", "Decision Locked"/);
  assert.doesNotMatch(pageSource, /"Knowledge Source", "Decision Locked", "WOH Buy\/Make Rule"/);
  assert.match(pageSource, /Mapping exact\/component suggestions accept only blank, Buy, or Local items/);
  assert.match(pageSource, /wohIsMappingComponentEligible/);
  assert.match(pageSource, /Import completed Rule Lab JSON/);
  assert.match(pageSource, /const EBAY_MAPPING_MASTER_FILE_ID = "1tI67Ykv9NcCQXpJfF4Ntekjm7nZPzJAG"/);
  assert.match(pageSource, /const CHANNEL_MAPPING_MASTER_FILE_ID = "1M-NcnS3cJ4BJ24Ybf8L8RKd-9cnBK735"/);
  assert.match(pageSource, /const SHIPSTATION_TRANSLATION_MASTER_FILE_ID = "1vKv2KvmeafVdvvuKVEMzdkhQlJQw1ceR"/);
  assert.match(pageSource, /getDriveFileById\(token, EBAY_MAPPING_MASTER_FILE_ID, EBAY_MAPPING_MASTER_NAME\)/);
  assert.match(pageSource, /writeDriveWorkbook\(token, EBAY_MAPPING_FOLDER_ID, EBAY_MAPPING_MASTER_NAME, ebayMappingMasterWorkbook\(mappings, importedAt\), EBAY_MAPPING_MASTER_FILE_ID\)/);
  assert.match(pageSource, /StockLens Channel WOH Mapping Rules/);
  assert.doesNotMatch(pageSource, /Math\.max\(1, Number\(component\.quantity \|\| 1\)\)/);
  assert.match(pageSource, /Number\(line\.quantity \|\| 0\) \* assemblyQuantity\(component\.quantity\)/);
  assert.match(pageSource, /WOH Local items always use a fixed eBay quantity of 5/);
  assert.match(pageSource, /WOH Buy\/Make is Local · fixed eBay quantity 5/);
  assert.match(pageSource, /item\.wohMakeBuy !== "Local"/);
  assert.match(pageSource, /loadEbayAbcMappingRows\(token\)/);
  assert.match(pageSource, /Authoritative mapping source: \{EBAY_MAPPING_MASTER_NAME\}/);
  assert.match(pageSource, /stocklens-restock-layout/);
  assert.match(pageSource, /stocklens-restock-table-width/);
  assert.match(pageSource, /stocklens-restock-column-order-v1/);
  assert.match(pageSource, /Horizontal scroll/);
  assert.match(pageSource, /Order Rec LT/);
  assert.match(pageSource, /WOH Order Rec/);
  assert.match(pageSource, /Start new analysis/);
  assert.match(pageSource, /Open saved analysis/);
  assert.match(pageSource, /Keep forever/);
  assert.match(pageSource, /stocklens-forecast-analysis-master\.xlsx/);
  assert.match(pageSource, /PERMANENT QUANTITY OVERRIDE HISTORY/);
  assert.match(pageSource, /Set final eBay quantity/);
  assert.match(pageSource, /Save final quantity/);
  assert.match(pageSource, /Use calculated quantity/);
  assert.match(pageSource, /Override app quantity/);
  assert.match(pageSource, /stocklens-ebay-zero-review-widths-v1/);
  assert.match(pageSource, /stocklens-ebay-review-console-widths-v1/);
  assert.match(pageSource, /Current eBay quantity/);
  assert.match(pageSource, /confirmed-alternate-path/);
  assert.match(pageSource, /Alternate Quantity per Original/);
  assert.match(pageSource, /Component Quantity per Alternate/);
  assert.match(pageSource, /Confirm alternate & quantity/);
  assert.match(pageSource, /quantityPerOriginal/);
  assert.match(pageSource, /EBAY_INVENTORY_EQUIVALENTS_MASTER_FILE_ID/);
  assert.match(pageSource, /ebayEquivalentEffectiveComponents\(path, multiplier\)/);
  assert.match(pageSource, /className="ebay-listing-link" href=\{`https:\/\/www\.ebay\.com\/itm\/\$\{encodeURIComponent/);
  assert.match(pageSource, /Current eBay qty/);
  assert.match(pageSource, /Suggested qty/);
  assert.match(pageSource, /ebayEquivalentReviewFilter === "Unconfirmed"/);
  assert.match(styles, /\.adjustable-table-wrap \{[^}]*overflow-x: scroll/);
  assert.match(pageSource, /LIVE PROCESS STATUS/);
  assert.match(pageSource, /accountingCostIndex/);
  assert.match(pageSource, /Build consolidated month totals/);
  assert.match(pageSource, /accountingRows\.map/);
  assert.match(styles, /\.accounting-process-panel/);
  assert.match(pageSource, /SECOND REVIEW · 0 → POSITIVE QUANTITY/);
  assert.match(pageSource, /zeroRestorationBlockers/);
  assert.match(pageSource, /item\.currentQuantity === 0/);
  assert.match(pageSource, /neither the mapped component nor a confirmed alternate has enough inventory/);
  assert.match(pageSource, /combinedPathCapacity/);
  assert.match(pageSource, /combinedPathCapacity\(requirement, stock\) >= 5/);
  assert.match(pageSource, /minimumOneGuaranteedKeys/);
  assert.match(pageSource, /minimum quantity 1 guaranteed/);
  assert.doesNotMatch(pageSource, /allocationStock\.set/);
  assert.doesNotMatch(pageSource, /\(stock\.get\(key\) \|\| 0\) \* 3/);
  assert.match(pageSource, /ebayZeroToPositiveApprovals\[item\.key\] === item\.recommendedQuantity/);
  assert.doesNotMatch(pageSource, /setEbayZeroToPositiveApprovals\(\{\}\)/);
  assert.match(pageSource, /"limited-inv", "Limited Inv"/);
  assert.match(pageSource, /limitedInventoryComponents/);
  assert.doesNotMatch(pageSource, /a saved equivalent cannot bypass a zero balance in an original mapped component/);
  assert.match(pageSource, /reserveCompleteComponentSet/);
  assert.match(pageSource, /if \(completed\) return completed/);
  assert.match(pageSource, /scarce stock cannot be promised twice/);
  assert.match(workerSource, /item\.requirements\.every/);
  assert.match(workerSource, /remaining\.set\(key, \(remaining\.get\(key\) \|\| 0\) - requirement\.quantityPerListing\)/);
  assert.match(pageSource, /Process marked quantities/);
  assert.match(pageSource, /Mark all pending/);
  assert.match(pageSource, /ebayZeroToPositiveStagedRef/);
  assert.match(pageSource, /input\[data-zero-positive-key\]:checked/);
  assert.match(pageSource, /Nothing was processed\. Mark at least one pending quantity/);
  assert.match(pageSource, /BACKGROUND PROCESS/);
  assert.match(pageSource, /Rebuild upload eligibility/);
  assert.doesNotMatch(pageSource, /ebayZeroToPositiveBatchButtonRef/);
  assert.match(pageSource, /Mark quantity for batch/);
  assert.match(styles, /tr\.zero-positive-staged td/);
  assert.match(styles, /\.zero-positive-process-panel/);
  assert.match(styles, /\.equivalent-component-row \{[^}]*flex-direction: column/);
  assert.match(pageSource, /Pending — excluded from upload/);
  assert.match(pageSource, /Save override & accept/);
  assert.doesNotMatch(pageSource, /CONTROLLED API TEST/);
  assert.doesNotMatch(pageSource, /ebayQuantityApiTest/);
  assert.doesNotMatch(workerSource, /\/api\/ebay\/inventory\/quantity-test/);
  assert.match(pageSource, /window\.open\("\/setup\/google-drive", "_blank", "noopener,noreferrer"\)/);
  assert.match(pageSource, /Open secure setup in a new tab/);
  assert.match(workerSource, /Continue with saved secret/);
  assert.match(workerSource, /already saved · leave blank to reuse/);
  assert.match(workerSource, /target="_top"/);
  assert.match(workerSource, /LIVE CONNECTION PROGRESS/);
  assert.match(workerSource, /Google callback received/);
  assert.match(workerSource, /Verify inventory sources/);
  assert.match(workerSource, /Open Google authorization in a new tab/);
  assert.match(workerSource, /googleDriveAuthorizationProgressPage\(authorize\.toString\(\)\)/);
  assert.match(pageSource, /EBAY_ZERO_TO_POSITIVE_OVERRIDE_REASONS/);
  assert.match(pageSource, /ebayInventoryUploadRows/);
  assert.match(pageSource, /function isGoogleDriveAuthenticationError/);
  assert.match(pageSource, /tokenRef\.current = null/);
  assert.match(pageSource, /Google Drive access expired\. Your alternate decisions are still on this page/);
  assert.match(pageSource, /EBAY_SHIPPING_LABEL_INBOX_FOLDER_ID/);
  assert.match(pageSource, /1dD5tOOPckpcWIvIxUp199kTr0eQGSHlX/);
  assert.doesNotMatch(pageSource, /const STOCK_FILE_ID/);
  assert.doesNotMatch(pageSource, /const readLiveStockUnits/);
  assert.match(pageSource, /void preloadSessionInventorySources\(\)/);
  assert.match(pageSource, /sessionWohRowsPromiseRef/);
  assert.match(pageSource, /sessionInventoryMovesPromiseRef/);
  assert.match(pageSource, /sessionMovementRowsPromiseRef/);
  assert.match(pageSource, /loadInventoryMovesBuffer\(token\)/);
  assert.doesNotMatch(pageSource, /INVENTORY_MOVES_FILE_ID/);
  assert.match(pageSource, /inventory transactions cached for this session/);
  assert.match(pageSource, /const unitsByItem = readEndPositionUnits\(inventoryMovesBuffer\)/);
  assert.match(pageSource, /"Stock Source Status": units === undefined \? "Missing" : "Calculated"/);
  assert.match(pageSource, /Current inventory could not be calculated from \$\{INVENTORY_MOVES_FILE_NAME\}/);
  assert.match(workerSource, /const refreshNightlyInventorySnapshot/);
  assert.match(workerSource, /const inventoryRefresh = await refreshNightlyInventorySnapshot\(env, snapshotItems\);/);
  assert.match(workerSource, /inventoryRefresh\.rows, payload\.listings/);
  assert.match(workerSource, /Automatic Google Drive inventory refresh is not connected/);
  assert.match(workerSource, /eBay data was not fetched/);
  assert.match(pageSource, /function syncEbayShippingLabelInbox/);
  assert.match(pageSource, /Check inbox now/);
  assert.match(pageSource, /Manual fallback · choose CSV/);
  assert.match(pageSource, /Drag a column-heading divider/);
  assert.match(pageSource, /Resize .* column/);
  assert.match(pageSource, /OPENED FROM RESTOCK/);
  assert.match(pageSource, /Edit eBay\/WOH mapping/);
  assert.match(pageSource, /Review every eBay parent shown by the filter/);
  assert.match(pageSource, /Return to Restock/);
  assert.match(pageSource, /missingWohAssemblyComponents/);
  assert.match(pageSource, /Open eBay\/WOH Mapping to correct/);
  assert.match(pageSource, /OPENED FROM EBAY ABC EXCEPTION/);
  assert.match(pageSource, /Return to eBay ABC/);
  assert.match(pageSource, /field === "SKU" \? "sku" : field/);
  assert.match(pageSource, /exactDirectMatch && !savedUserDecision/);
  assert.match(pageSource, /savedAutomaticMakeSuggestion/);
  assert.match(pageSource, /Automatic Buy\/Make decision cleared · normal matching restored/);
  assert.doesNotMatch(pageSource, /makeRulePending/);
  assert.match(styles, /\.abc-missing-component-reason button/);
});
